### ISSUE TITLE
Avare connection to pilot

### ISSUE THREAD

**Issue by D35Bonanza** [dndx/pitot#1] opened 2017-07-03 03:22 UTC
Installed the current release, shh into it, root is now RW.

I connect my EFB Nexus 7 android to the Pilot SSID wifi obtain ip address then start Avare external IO on wifi port 4000, it connects however it disconnects without dataflow starting. The IP address is valid.
 It could be my SDRs and GPS are not installed yet.

On ssh into pilot netstat -u shows no UDP connections.
Given the nature of development I will load a new Jessica image and git clone the sources and see if a build can be successful.

I normally use eth0 as an inetv4 connnection as well as wlan0 both are DHCP inetv4

**Comment by dndx** [comment] 2017-07-03 03:30
Hmm, that is really strange. Could you SSH into your Pitot build and run `sudo journalctl -u pitot` to see what it is outputting? `netstat -u` showing no UDP connection is also strange as Pitot will maintain open UDP connection for each host present in the lease file. Is your Nexus 7 using DHCP for acquiring IP address?

**Comment by D35Bonanza** [comment] 2017-07-03 03:48
Yes it is using DHCP it aquires 192.168.0.33

I will have to check it out and do a build on Rpi jessie

**Comment by D35Bonanza** [comment] 2017-07-03 16:51
Hello
I cannot clone dump978 or dump1090
I get
Permission denied (publickey) 
git clone https://github.com/dndx/pitot.git worked just fine.

**Comment by D35Bonanza** [comment] 2017-07-03 20:08
Ok git the dump978 and dump1090 install.
cargo build Give the following;
arning: struct is never used: `FakeGNSSProvider`
  --> src/sensor/gnss/fake.rs:22:1
   |
22 | struct FakeGNSSProvider {}
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: #[warn(dead_code)] on by default

warning: method is never used: `new`
  --> src/sensor/gnss/fake.rs:45:5
   |
45 | /     fn new() -> Option<Box<Self>> {
46 | |         Some(Box::new(FakeGNSSProvider {}))
47 | |     }
   | |_____^
   |
   = note: #[warn(dead_code)] on by default

error: linking with `cc` failed: exit code: 1
...
 = note: /root/pitot/target/debug/deps/pitot-a7ad4ae01c7d6b88.0.o: In function `pitot::sensor::sdr::bindings::librtlsdr::{{impl}}::set_tuner_bandwidth':
          /root/pitot/src/sensor/sdr/bindings/librtlsdr.rs:182: undefined reference to `rtlsdr_set_tuner_bandwidth'
          collect2: error: ld returned 1 exit status
          

error: aborting due to previous error

error: Could not compile `pitot`.

To learn more, run the command again with --verbose.
root@raspberrypi:~/pitot#

**Comment by dndx** [comment] 2017-07-03 23:14
I remember seeing this at some point. I think it's caused by an older version of `librtlsdr`. Could you try to compile and install `librtlsdr` from their `master` and try again?

You can use https://github.com/dndx/rpi-img-builder/blob/pitot/plugins/pitot/postinst#L11-L15 as a reference on how to do that.

**Comment by D35Bonanza** [comment] 2017-07-04 01:22
OK here what I did
Add the two Debian package signing keys:

sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 7638D0442B90D010
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 8B48AD6246925553

Add the Backports repository:

add 'deb http://httpredir.debian.org/debian jessie-backports main contrib non-free'
to /etc/apt/sources.list

Update your package lists:

sudo apt-get update
apt-get -t jessie-backports install librtlsdr-dev
root@raspberrypi:~/pitot# cargo build
   Compiling pitot v0.1.0 (file:///root/pitot)
warning: struct is never used: `FakeGNSSProvider`
  --> src/sensor/gnss/fake.rs:22:1
   |
22 | struct FakeGNSSProvider {}
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: #[warn(dead_code)] on by default

warning: method is never used: `new`
  --> src/sensor/gnss/fake.rs:45:5
   |
45 | /     fn new() -> Option<Box<Self>> {
46 | |         Some(Box::new(FakeGNSSProvider {}))
47 | |     }
   | |_____^
   |
   = note: #[warn(dead_code)] on by default

    Finished dev [unoptimized + debuginfo] target(s) in 78.94 secs

Before I do make install, is there anything else to do?

**Comment by D35Bonanza** [comment] 2017-07-04 01:29
Ran

root@raspberrypi:~/pitot/target/debug# ./pitot
thread 'main' panicked at 'could not configure serial port: Io(Error { repr: Custom(Custom { kind: TimedOut, error: StringError("Operation timed out") }) })', /checkout/src/libcore/result.rs:859
note: Run with `RUST_BACKTRACE=1` for a backtrace.
root@raspberrypi:~/pitot/target/debug#

**Comment by D35Bonanza** [comment] 2017-07-04 14:53
Ok the above error maybe I do not have a ry38* insatall, I do have a ry385 that I can use.
It appears good news give cargo test
root@raspberrypi:~/pitot# cargo test
   Compiling pitot v0.1.0 (file:///root/pitot)
    Finished dev [unoptimized + debuginfo] target(s) in 82.85 secs
     Running target/debug/deps/pitot-b3d0ee29309d8751

running 10 tests
test protocol::gdl90::tests::test_crs_to_gdl90 ... ok
test protocol::gdl90::tests::test_alt_to_gdl90 ... ok
test processor::traffic::tests::test_icao_to_tail ... ok
test protocol::gdl90::tests::test_generate_traffic ... ok
test sensor::gnss::ublox::tests::test_make_ubx_message ... ok
test sensor::gnss::fake::tests::test_fake_gnss_provider ... ok
test sensor::gnss::ublox::tests::test_ubx_parser ... ok
test sensor::sdr::uat::tests::test_parse_adsb_downlink ... ok
test sensor::sdr::bindings::librtlsdr::tests::test_get_device_count ... ok
test sensor::sdr::bindings::librtlsdr::tests::test_new_nx_device ... ok

test result: ok. 10 passed; 0 failed; 0 ignored; 0 measured

root@raspberrypi:~/pitot# 
pitot will not start yet

**Comment by D35Bonanza** [comment] 2017-07-04 17:43
Hello

Loaded the debug disk image once again. I have the ry385 now attached to the Rpi3 and working. SRD stx 978 and 1090.

Attached two Avare Nexus 7 to pitot wifi. It is working.
Here is the output from the ssh login.
pi@pitot-b335944fec74:~$ netstat -u
Active Internet connections (w/o servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State
udp        0      0 192.168.0.1:44973       192.168.0.33:4000       ESTABLISHED
udp        0      0 192.168.0.1:49253       192.168.0.46:4000       ESTABLISHED
udp        0      0 192.168.0.1:37535       192.168.0.47:4000       ESTABLISHED
pi@pitot-b335944fec74:~$
pi@pitot-b335944fec74:~$ sudo journalctl -u pitot
-- Logs begin at Tue 2017-07-04 17:22:31 UTC, end at Tue 2017-07-04 17:37:07 UTC. --
Jul 04 17:22:33 pitot-b335944fec74 systemd[1]: Starting Pitot ADS-B Receiver...
Jul 04 17:22:33 pitot-b335944fec74 systemd[1]: Started Pitot ADS-B Receiver.
Jul 04 17:22:33 pitot-b335944fec74 pitot[408]: INFO:pitot::sensor::gnss::ublox: trying port /dev/ttyAMA0
Jul 04 17:22:34 pitot-b335944fec74 pitot[408]: INFO:pitot::sensor::gnss::ublox: chip supports Galileo
Jul 04 17:22:34 pitot-b335944fec74 pitot[408]: Found Rafael Micro R820T tuner
Jul 04 17:22:35 pitot-b335944fec74 pitot[408]: [R82XX] PLL not locked!
Jul 04 17:22:35 pitot-b335944fec74 pitot[408]: INFO:pitot::sensor::sdr::es: 1090ES initialization successful
Jul 04 17:22:35 pitot-b335944fec74 pitot[408]: Found Rafael Micro R820T tuner
Jul 04 17:22:35 pitot-b335944fec74 pitot[408]: Exact sample rate is: 2083334.141630 Hz
Jul 04 17:22:35 pitot-b335944fec74 pitot[408]: [R82XX] PLL not locked!
Jul 04 17:22:36 pitot-b335944fec74 pitot[408]: INFO:pitot::sensor::sdr::uat: UAT initialization successful
Jul 04 17:22:36 pitot-b335944fec74 pitot[408]: INFO:ws: Listening for new connections on 0.0.0.0:9001.
Jul 04 17:22:50 pitot-b335944fec74 pitot[408]: INFO:pitot::processor::clock: setting system clock
Jul 04 17:23:32 pitot-b335944fec74 pitot[408]: INFO:pitot::transport::udp: new client: 192.168.0.33
Jul 04 17:25:02 pitot-b335944fec74 pitot[408]: INFO:pitot::transport::udp: new client: 192.168.0.46
Jul 04 17:31:48 pitot-b335944fec74 pitot[408]: INFO:pitot::transport::udp: new client: 192.168.0.47

If you can help me just my Jessie build configured this would be great.

**Comment by dndx** [comment] 2017-07-05 03:03
@D35Bonanza The Ublox sensor module assumes a GPS is connected whenever `/dev/ttyAMA0` exists, and it will panic if couldn't get anything back on that port. This is not the intended result and will be fixed for sure.

If you want to run Pitot on your own Linux image, you need to tweak a few things, most notably to disable the default Linux serial console on `/dev/ttyAMA0` and disable Bluetooth. You can check your `/boot/cmdline.txt` and `/boot/config.txt` file in the official image to see how that was done.

**Comment by D35Bonanza** [comment] 2017-07-05 04:06
Ok cool

I just got eth0 connected to my router and now I can get to pitot via ligthdm mate and xrdp 
for some reason eth0 would fall back to inet6 and I need to use inet4. so RO is off on the sd card now 
Pitot is feeding three Avare clients and doing just fine

**Comment by dndx** [comment] 2017-07-05 04:42
@D35Bonanza It's probably because I disabled `eth0`. You can edit https://github.com/dndx/rpi-img-builder/blob/35afbc74b09667e9b5d3478ca44416ea7de93fac/plugins/common/files/etc/network/interfaces.d/eth0.cfg#L2 to give it an IP address and then turn back on the RO mode.

**Comment by D35Bonanza** [comment] 2017-07-05 13:15
Yes I know I did change the entry for eth0 to be dhcp, however the inet is putting inet6 address on the interface. The only way I could get inet4 was a static address and route add to the IP table so the interface would be on the internet. I think I will there the file systems on RW for development purposes. I is not clear you can place the pitot source on a stratux jessie image and have it compile without additional packages,

Today I try and get the new latest Jessie image running.
Have you looked at https://github.com/westphae/goflying.git  yet?

**Comment by dndx** [comment] 2017-07-06 06:16
@D35Bonanza I think Pitot image does not contain a DHCP client (server only), thus it will not work if you tries to use DHCP with `eth0.cfg`.

For running Pitot with Stratux in the same system, the biggest issue will be the incompatibility of `libdump978`, which I kinda mentioned inside [DEVELOPING.md](https://github.com/dndx/pitot/blob/master/DEVELOPING.md).

**Comment by D35Bonanza** [comment] 2017-07-07 03:00
Ok dndx. I got my SDcards finally worked out. Pitot is running fine. I got the cmdline and bootconfig install on my new jessie image, The app was cargo build again it now starts without out panic, however the package udhcpd is not yet installed. I have the pkg install list so I will update the jessie image and see if it starts up correctly. 

Just a note the targets on Avare falls off and then comes back in a few seconds if they have a weak signal. Stratux does not drop them so quickly maybe 5sec before drop would help.

I set eth0 up static, the default manual is supposed to give DHCP as does the jessie image.
/etc/resolv.conf was not present so I did touch it and add nameserver entries. eth0 is up on the net and working. I'm using the pitot image to make this post.
iface... eth0
netmask
gateway
nameserver
in interfaces

I'll let you know further as testing goes on

**Comment by D35Bonanza** [comment] 2017-07-16 00:03
Hello dxdn

I finally had time to play with rpi-img-builder, It now working correctly, Pitot is running fine. Pitot performs as good as Stratux and with less GPS dropouts. @dndx 20% cpu usage. pitot is working away The SDRs get a bit hotter this is for sure, Mine are conduction cooled. UAT fisb and es1090 is working great. Now to start learning RUST.

**Comment by dndx** [comment] 2017-07-22 23:55
Good. Closing this issue for now.

**Closed by dndx** 2017-07-22 23:55 UTC
